import re  # Стандартная библиотека для поиска текста
from Bio import Entrez  # Библиотека для работы с биологическими БД
from clinvar_api import get_clinvar_significance_for_list, load_rs_from_file  # новый модуль связи с ClinVar

def universal_genomic_scanner(sequence):
    print("\n" + "="*45)
    print("🚀 STARTING MULTI-LEVEL GENOMIC SCAN v3.0")
    print("="*45)
    
    # 1. Расчет GC-состава
    gc = (sequence.count('G') + sequence.count('C')) / len(sequence) * 100
    print(f"📊 [STRUCTURAL] GC-Content: {gc:.2f}%")
    
    # 2. ПРОВЕРКА ПОВТОРОВ (HTT)
    repeats = re.findall(r'(?:CAG){3,}', sequence)
    if repeats:
        count = len(max(repeats, key=len)) // 3
        status = "⚠️ PATHOGENIC" if count >= 36 else "✅ NORMAL"
        print(f"🧬 [REPEATS] HTT Gene: {count} CAG repeats ({status})")
    else:
        print(f"🧬 [REPEATS] HTT Gene: No expansions detected (Normal)")

    # 3. ПРОВЕРКА SIRT1 (Долголетие)
    if sequence[0] == 'G':
        print("🌟 [BIOHACK] SIRT1: Longevity Variant 'G' detected!")
        print("🔍 Connecting to ClinVar to verify...")
        clinical_status = get_clinvar_significance('rs7069102') 
        print(f"   └─ Official Scientific Status: {clinical_status}")

    # 4. ПРОВЕРКА LRP5 (Кости-титан)
    if len(sequence) > 171 and sequence[171] == 'T':
        print("🦾 [SUPERPOWER] LRP5: High Bone Density variant found!")
        print("🔍 Verifying Clinical Significance...")
        clinical_status = get_clinvar_significance('rs121908675')
        print(f"   └─ ClinVar Result: {clinical_status}")

    # 5. ПРОВЕРКА TERT (Кнопка рака)
    if len(sequence) > 228 and sequence[228] == 'T':
        print("🚨 [CANCER RISK] TERT Promoter Mutation Found (C228T)")

    print("="*45 + "\n")

# ТЕСТОВЫЕ ДАННЫЕ (Полная проверка всех систем)
# Добавили CAG-повторы, чтобы пункт 2 тоже сработал
super_human_dna = "G" + ("CAG" * 40) + ("A" * 48) + "T" + ("A" * 56) + "T" + ("C" * 20)
universal_genomic_scanner(super_human_dna)

def generate_professional_report(input_file):
    """
    Массовая проверка мутаций из файла и создание красивого отчета.
    """
    print("\n" + "═"*60)
    print("📋 GENOMIC ANOMALY ATLAS: DIAGNOSTIC REPORT")
    print("═"*60)
    
    # 1. Загрузка
    rs_list = load_rs_from_file(input_file)
    if not rs_list:
        print("❌ Error: No variants loaded. Check your rs_numbers.txt")
        return
    
    print(f"✅ Loaded {len(rs_list)} variants. Querying NCBI databases...")
    
    # 2. Пакетная проверка через API
    results = get_clinvar_significance_for_list(rs_list)
    
    # 3. Формирование визуального отчета
    print("\n[ ANALYSIS RESULTS ]")
    print("-" * 30)
    for rs, status in results.items():
        # Присваиваем иконку в зависимости от статуса
        if "Pathogenic" in status:
            icon = "🔴 [High Risk]"
        elif "Benign" in status:
            icon = "🟢 [Safe]"
        else:
            icon = "🔵 [Review Needed]"
            
        print(f"{icon} {rs.upper()}: {status}")
    
    print("\n" + "═"*60)
    print("Generated by Genomic Anomaly Atlas Pipeline v3.0")
    print("Date: 2024 | Medical data for research purposes only.")
    print("═"*60 + "\n")

# --- ЗАПУСК ---
if __name__ == "__main__":
    # 1. Проверяем сырую ДНК (твой тестовый образец)
    test_dna = "G" + ("CAG" * 40) + ("A" * 48) + "T" + ("A" * 56) + "T" + ("C" * 20)
    universal_genomic_scanner(test_dna)
    
    # 2. Запускаем массовую проверку из файла
    generate_professional_report("rs_numbers.txt")
